name: Build and Upload Packs

on:
  push:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Run Script
        run: |
          chmod +x .github/scripts/buildpack.main.kts 
          .github/scripts/buildpack.main.kts
