name: Build and Upload Packs

on:
  push:
    branches: [ "*" ]

jobs:
  build:
    strategy:
      matrix:
        include:
          - name: Darkmode Mist
            id: darkmode_mist
          - name: Deep Hollows
            id: deep_hollows
          - name: Overgrown Tunnels
            id: overgrown_tunnels
          - name: Fancy Panes
            id: fancy_panes

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Upload ${{ matrix.name }} Pack
        uses : actions/upload-artifact@v7
        with:
          name: ${{ matrix.name }}
          path: ${{ matrix.id }}/*
